// Remove the retired Google Drive connection preference only.
try{localStorage.removeItem('one-cup-drive-connected-v1')}catch{}
'use strict';
const $=id=>document.getElementById(id), KEY='one-cup-recipes-v1';
const TYPES={HOT:'HOT',ICED:'ICE',FRAPPUCCINO_BLENDED:'프라푸치노/블렌디드',FIZZIO_REFRESHER:'피지오/리프레셔',TRENTA_DELIVERS:'트렌타/딜리버스',PROMOTION:'프로모션',OTHER:'기타'};
const SIZES={SOLO:'Solo',DOPPIO:'Doppio',SHORT:'Short',TALL:'Tall',GRANDE:'Grande',VENTI:'Venti',TRENTA:'Trenta'};
function sizeKey(value){if(Object.hasOwn(SIZES,value))return value;const found=Object.entries(SIZES).find(([,label])=>label===value);return found?found[0]:value==='사용법 예시'?'EXAMPLE':value}
function sizeLabel(value){return SIZES[value]||value||'사이즈 미지정'}
const QUANTITIES={shots:'샷',syrup:'시럽',additives:'첨가물'};
function quantities(r){return Object.entries(QUANTITIES).filter(([k])=>r[k]!==undefined&&r[k]!=='').map(([k,label])=>label+' '+r[k]+'회').join(' · ')}
const demos=[{id:'demo-latte',name:'카페 라떼',size:'사용법 예시',temperature:'HOT',ingredients:'에스프레소\n우유\n※ 실제 수량은 매장 레시피로 입력하세요.',steps:'매장 기준에 따라 에스프레소와 스팀 밀크를 준비해요.\n에스프레소에 스팀 밀크를 부어요.',first:'매장에서 배운 첫 동작으로 수정해 주세요.',note:'공식 제조 순서가 아닌 연습용 예시입니다.',demo:true},{id:'demo-americano',name:'아이스 아메리카노',size:'사용법 예시',temperature:'ICED',ingredients:'에스프레소\n물\n얼음\n※ 실제 수량은 매장 레시피로 입력하세요.',steps:'에스프레소, 물, 얼음을 준비해요.\n실제 제조 순서는 매장 레시피에 맞게 수정해 주세요.',first:'매장에서 배운 첫 동작으로 수정해 주세요.',note:'공식 제조 순서가 아닌 연습용 예시입니다.',demo:true}];
let data={recipes:demos,record:{}},queue=[],index=0,correct=0,answered=false,editing=null;
try{const raw=localStorage.getItem(KEY);if(raw){const d=normalizeBackup(JSON.parse(raw));if(d)data=d;}}catch{setTimeout(()=>toast('저장된 데이터를 읽지 못했어요. 백업이 있으면 불러와 주세요.'),100)}
function valid(d){return d&&Array.isArray(d.recipes)&&d.recipes.length<=2000&&d.record&&typeof d.record==='object'&&!Array.isArray(d.record)&&new Set(d.recipes.map(r=>r.id)).size===d.recipes.length&&d.recipes.every(r=>r&&['id','name','size','temperature','ingredients','steps','first'].every(k=>typeof r[k]==='string'&&r[k].length<20000)&&r.id.trim().length>0&&r.name.trim().length>0&&Object.hasOwn(TYPES,r.temperature)&&Object.keys(QUANTITIES).every(k=>r[k]===undefined||(typeof r[k]==='string'&&(r[k]===''||(/^(?:0|[1-9]\d*)(?:\.5)?$/.test(r[k])&&Number.isFinite(Number(r[k]))))))&&(r.note===undefined||typeof r.note==='string'));}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));return true}catch{toast('저장 공간을 사용할 수 없어요. 백업 저장으로 보관해 주세요.');return false}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let toastTimer;function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4500)}
let currentTab='practice';
function tab(name){currentTab=name;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$('practice').hidden=name!=='practice';$('random-quiz').hidden=name!=='random-quiz';$('recipes').hidden=name!=='recipes';$('backup').hidden=true;const settings=$('settings-button');settings.classList.remove('active');settings.setAttribute('aria-expanded','false');settings.setAttribute('aria-label','설정 열기');if(name==='recipes')list();if(name==='random-quiz')updateRandomAvailable()}
function toggleSettings(){const open=$('backup').hidden;if(open){document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));$('practice').hidden=true;$('random-quiz').hidden=true;$('recipes').hidden=true;$('backup').hidden=false;const settings=$('settings-button');settings.classList.add('active');settings.setAttribute('aria-expanded','true');settings.setAttribute('aria-label','설정 닫기')}else tab(currentTab)}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
$('settings-button').onclick=toggleSettings;
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function resetPractice(){queue=[];index=0;correct=0;answered=false;$('practice-setup').hidden=false;$('practice-cards').hidden=true;$('practice-summary').hidden=true;$('quiz-card').innerHTML='';$('count').textContent=data.recipes.length;$('done').textContent='0';$('correct').textContent='0'}
function start(){queue=shuffle(data.recipes.filter(r=>($('temp').value==='all'||r.temperature===$('temp').value)&&($('filter').value==='all'||($('filter').value==='wrong'?data.record[r.id]?.wrong:!data.record[r.id]?.attempts))).map(r=>r.id));index=0;correct=0;if(!queue.length){resetPractice();$('practice-summary').textContent='연습할 레시피가 없어요. 분류를 바꾸거나 내 레시피에서 추가해 주세요.';$('practice-summary').hidden=false;return}$('practice-setup').hidden=true;$('practice-cards').hidden=false;$('practice-summary').hidden=true;render()}
function render(){answered=false;$('count').textContent=data.recipes.length;$('done').textContent=index;$('correct').textContent=correct;$('bar').style.width=(queue.length?index/queue.length*100:0)+'%';$('position').textContent=queue.length?`${Math.min(index+1,queue.length)} / ${queue.length}`:'';const card=$('quiz-card');
if(!queue.length){card.innerHTML='<div class="complete-symbol">☕</div><h2>연습할 카드가 없어요</h2><p class="question">필터를 바꾸거나 새 레시피를 추가해 주세요.</p><button class="primary reveal" id="empty-add">내 레시피 보기</button>';$('empty-add').onclick=()=>tab('recipes');return}
if(index>=queue.length){$('practice-setup').hidden=false;$('practice-cards').hidden=true;$('practice-summary').textContent=`연습 완료! ${queue.length}잔 중 ${correct}잔을 기억했어요.`;$('practice-summary').hidden=false;return}
$('session-label').textContent=$('mode').value==='first'?'첫 행동 연습':'레시피 떠올리기';const r=data.recipes.find(r=>r.id===queue[index]);if(!r){index++;render();return}card.innerHTML=`<div class="badges"><span class="badge ${r.temperature.toLowerCase()}">${esc(TYPES[r.temperature]||r.temperature)}</span><span class="badge">${esc(sizeLabel(r.size))}</span>${r.demo?'<span class="badge">연습용 예시</span>':''}</div><h2>${esc(r.name)}</h2><p class="question">${$('mode').value==='first'?'이 음료를 시작할 때, 가장 먼저 할 행동은?':'어떤 재료로, 어떤 순서로 만들까요?'}</p><textarea id="guess" aria-label="내가 떠올린 답" placeholder="기억나는 대로 적어보세요. (선택)"></textarea><div id="answer-area"></div><button id="reveal" class="primary reveal">정답 확인하기 ↓</button>${r.demo?'<p class="small center">사용법 예시 · 공식 레시피가 아닙니다.</p>':''}`;
$('reveal').onclick=()=>{if(answered)return;answered=true;$('reveal').hidden=true;$('guess').readOnly=true;let html=$('mode').value==='first'?`<h3>첫 행동</h3><p>${esc(r.first||'아직 입력하지 않았어요.')}</p>`:`<h3>재료</h3><p>${esc(r.ingredients||'아직 입력하지 않았어요.')}</p>${quantities(r)?`<h3>샷 · 시럽 · 첨가물 횟수</h3><p>${esc(quantities(r))}</p>`:''}<h3>제조 순서</h3><p>${esc(r.steps||'아직 입력하지 않았어요.')}</p>`;if(r.note)html+=`<h3>기억할 점</h3><p>${esc(r.note)}</p>`;$('answer-area').innerHTML=`<div class="answer">${html}</div><p class="small center">내 답과 비교하고 직접 체크해 주세요.</p><div class="grade"><button class="secondary" id="wrong">↻ 다시 연습할래요</button><button class="primary" id="right">✓ 기억했어요</button></div>`;$('wrong').onclick=()=>grade(false,r);$('right').onclick=()=>grade(true,r);};}
function grade(ok,r){data.record[r.id]={attempts:(data.record[r.id]?.attempts||0)+1,wrong:!ok};if(ok)correct++;save();index++;render()}
$('start').onclick=start;['mode','filter','temp'].forEach(id=>$(id).onchange=resetPractice);
let recipeReview='all';
let recipeCategory='all';
let recipeSize='all';
function list(){$('review-actions').hidden=recipeReview!=='wrong';$('bulk-actions').hidden=recipeReview==='wrong';const term=$('search').value.trim().toLowerCase();const pool=data.recipes.filter(r=>recipeReview==='all'||data.record[r.id]?.wrong);$('recipe-review').innerHTML=Object.entries({all:'전체 레시피',wrong:'다시 연습할 음료'}).map(([key,label])=>`<button type="button" class="category-chip ${recipeReview===key?'selected':''}" data-review="${key}" aria-pressed="${recipeReview===key}">${label} <span>${key==='all'?data.recipes.length:data.recipes.filter(r=>data.record[r.id]?.wrong).length}</span></button>`).join('');const rs=pool.filter(r=>(recipeCategory==='all'||r.temperature===recipeCategory)&&(recipeSize==='all'||sizeKey(r.size)===recipeSize)&&r.name.toLowerCase().includes(term));$('recipe-categories').innerHTML=Object.entries({all:'전체',...TYPES}).map(([key,label])=>{const n=pool.filter(r=>key==='all'||r.temperature===key).length;return `<button type="button" class="category-chip ${recipeCategory===key?'selected':''}" data-category="${key}" aria-pressed="${recipeCategory===key}">${label} <span>${n}</span></button>`}).join('');$('recipe-sizes').innerHTML=Object.entries({all:'전체',...SIZES}).map(([key,label])=>{const n=pool.filter(r=>(recipeCategory==='all'||r.temperature===recipeCategory)&&(key==='all'||sizeKey(r.size)===key)).length;return `<button type="button" class="category-chip size-chip ${recipeSize===key?'selected':''}" data-size="${key}" aria-pressed="${recipeSize===key}">${label} <span>${n}</span></button>`}).join('');$('recipe-results').textContent=(recipeReview==='wrong'?'다시 연습 · ':'')+(TYPES[recipeCategory]||'전체')+' · '+(SIZES[recipeSize]||'전체')+' · '+rs.length+'개'+(term?' 검색 결과':' 레시피');$('count').textContent=data.recipes.length;$('recipe-list').innerHTML=rs.length?rs.map(r=>`<article class="recipe-row"><label class="recipe-check"><input type="checkbox" data-select-id="${esc(r.id)}" aria-label="${esc(r.name)} 선택"><span></span></label><div class="recipe-info"><h3>${esc(r.name)}</h3><p>${esc(TYPES[r.temperature]||r.temperature)} · ${esc(sizeLabel(r.size))}${r.demo?' · 예시':''}${data.record[r.id]?.wrong?' <span class="review-badge">다시 연습</span>':''}</p></div><div class="row-actions"><button class="secondary" data-edit="${esc(r.id)}">수정</button>${recipeReview==='wrong'?`<button class="secondary" data-clear-review="${esc(r.id)}">표시 해제</button>`:`<button class="delete" data-delete="${esc(r.id)}">삭제</button>`}</div></article>`).join(''):(recipeReview==='wrong'?'<p class="empty">현재 조건에 다시 연습할 음료가 없어요.</p>':term?'<p class="empty">검색 결과가 없어요. 다른 이름이나 분류를 선택해 주세요.</p>':'<p class="empty">이 분류에 등록된 레시피가 없어요. 레시피를 추가해 보세요.</p>')}
$('recipe-review').onclick=e=>{const b=e.target.closest('button[data-review]');if(!b)return;recipeReview=b.dataset.review;list()};
$('recipe-categories').onclick=e=>{const b=e.target.closest('button[data-category]');if(!b)return;recipeCategory=b.dataset.category;list()};
$('recipe-sizes').onclick=e=>{const b=e.target.closest('button[data-size]');if(!b)return;recipeSize=b.dataset.size;list()};
$('search').oninput=list;$('delete-selected').onclick=()=>{const ids=[...document.querySelectorAll('[data-select-id]:checked')].map(x=>x.dataset.selectId);if(!ids.length)return toast('삭제할 레시피를 선택해 주세요.');if(!confirm(`선택한 ${ids.length}개 레시피와 해당 연습 기록을 삭제할까요?\n\n삭제 후에는 복구할 수 없어요.`))return;data.recipes=data.recipes.filter(r=>!ids.includes(r.id));ids.forEach(id=>delete data.record[id]);save();list();resetPractice();toast(`${ids.length}개 레시피를 삭제했어요.`)};$('delete-all').onclick=()=>{if(!data.recipes.length)return toast('삭제할 레시피가 없어요.');if(!confirm(`저장된 레시피 ${data.recipes.length}개와 연습 기록을 모두 삭제할까요?\n\n삭제 후에는 복구할 수 없어요. 필요한 데이터는 먼저 백업해 주세요.`))return;data.recipes=[];data.record={};save();list();resetPractice();toast('전체 레시피를 삭제했어요.')};$('recipe-list').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.clearReview){clearReviewFlags([b.dataset.clearReview]);return}if(b.dataset.edit)openEditor(b.dataset.edit);if(b.dataset.delete&&confirm('이 레시피와 연습 기록을 삭제할까요?')){data.recipes=data.recipes.filter(r=>r.id!==b.dataset.delete);delete data.record[b.dataset.delete];save();list();resetPractice()}};
function openEditor(id=null){editing=id;$('form').reset();if(!id&&recipeCategory!=='all')$('temperature').value=recipeCategory;if(!id&&recipeSize!=='all'&&Object.hasOwn(SIZES,recipeSize))$('size').value=recipeSize;$('form-title').textContent=id?'레시피 수정':'레시피 추가';if(id){const r=data.recipes.find(r=>r.id===id);['name','temperature','ingredients','steps','first','note','shots','syrup','additives'].forEach(k=>$(k).value=r[k]||'');const selected=sizeKey(r.size);if(!Object.hasOwn(SIZES,selected)){const legacy=document.createElement('option');legacy.value=selected;legacy.textContent=sizeLabel(r.size);legacy.dataset.legacy='true';$('size').append(legacy)}$('size').value=selected}$('editor').showModal()}
$('add').onclick=()=>openEditor();$('close').onclick=()=>$('editor').close();$('form').onsubmit=e=>{e.preventDefault();const r={id:editing||crypto.randomUUID(),demo:false};for(const k of ['name','size','temperature','ingredients','steps','first','note','shots','syrup','additives'])r[k]=$(k).value.trim();if(!r.name||!Object.hasOwn(TYPES,r.temperature))return toast('음료 이름과 음료 종류를 입력해 주세요.');if(editing){data.recipes=data.recipes.map(x=>x.id===editing?r:x);delete data.record[editing]}else data.recipes.push(r);if(recipeCategory!=='all')recipeCategory=r.temperature;const saved=save();$('editor').close();list();resetPractice();if(saved)toast('레시피를 저장했어요.')};
const BACKUP_FORMAT='one-cup-recipes';
function backupPayload(){return {format:BACKUP_FORMAT,formatVersion:2,exportedAt:new Date().toISOString(),recipes:data.recipes,record:data.record}}
function normalizeBackup(raw){const candidates=[raw,raw?.data,raw?.payload];for(const candidate of candidates){if(!candidate||!Array.isArray(candidate.recipes))continue;const migrated={recipes:candidate.recipes.map(r=>r&&['FRAPPUCCINO','BLENDED'].includes(r.temperature)?{...r,temperature:'FRAPPUCCINO_BLENDED'}:r),record:candidate.record};if(valid(migrated))return migrated}return null}
function backupFile(){const json=JSON.stringify(backupPayload(),null,2);return new File(['\ufeff'+json],'one-cup-recipes-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json',{type:'application/json;charset=utf-8'})}
$('export').onclick=()=>{const file=backupFile(),url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('백업 파일을 내려받아요. 파일 앱에 저장됐는지 확인해 주세요.')};
if(navigator.canShare&&navigator.canShare({files:[backupFile()]}))$('share-backup').hidden=false;
$('share-backup').onclick=async()=>{try{await navigator.share({files:[backupFile()],title:'한 잔씩 레시피 백업'});}catch(e){if(e.name!=='AbortError')toast('공유할 수 없어요. 백업 파일 저장 버튼을 이용해 주세요.')}};
$('import-btn').onclick=()=>$('import').click();$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5000000)throw Error();const raw=JSON.parse((await file.text()).replace(/^\uFEFF/,''));const d=normalizeBackup(raw);if(!d)throw Error();if(confirm(`현재 레시피를 백업의 ${d.recipes.length}개 레시피로 바꿀까요? 기존 데이터를 보관하려면 먼저 백업해 주세요.`)){data=d;const saved=save();list();resetPractice();if(saved)toast('PC·iPad·iPhone·갤럭시 공통 백업을 불러왔어요.')}}catch{toast('올바른 레시피 백업 파일을 선택해 주세요.')}e.target.value=''};
$('clear-data').onclick=async()=>{if(!confirm('이 기기의 레시피·연습 기록과 오프라인 앱 캐시를 모두 삭제할까요?\n\n삭제 후에는 되돌릴 수 없어요. 필요한 데이터는 먼저 백업 파일로 저장해 주세요. 앱 캐시를 삭제하면 오프라인 사용이 해제되며, 다시 사용하려면 인터넷 연결이 필요합니다. 백업 파일은 삭제되지 않습니다.'))return;window.dispatchEvent(new Event("one-cup-clearing"));data={recipes:[],record:{}};recipeCategory='all';recipeSize='all';save();try{if('caches' in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('one-cup-offline-'+encodeURIComponent(new URL('./',location.href).pathname)+'-')).map(k=>caches.delete(k)))}if('serviceWorker' in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.filter(reg=>reg.scope===new URL('./',location.href).href).map(reg=>reg.unregister()))}}catch{}list();resetPractice();toast('저장 데이터와 앱 캐시를 삭제했어요. 오프라인 사용을 다시 준비하려면 인터넷에서 새로고침하세요.');};
resetPractice();

function clearReviewFlags(ids){
 const targets=data.recipes.filter(r=>ids.includes(r.id)&&data.record[r.id]?.wrong);
 if(!targets.length)return toast('표시를 해제할 음료를 선택해 주세요.');
 if(!confirm(`${targets.length}개 음료의 다시 연습 표시를 해제할까요?\n레시피와 연습 횟수는 그대로 보관돼요.`))return;
 for(const r of targets)data.record[r.id]={...data.record[r.id],wrong:false};
 const saved=save();list();if(saved)toast(`${targets.length}개 음료의 다시 연습 표시를 해제했어요.`);
}
$('review-clear-selected').onclick=()=>clearReviewFlags([...document.querySelectorAll('[data-select-id]:checked')].map(x=>x.dataset.selectId));
$('review-clear-all').onclick=()=>clearReviewFlags(data.recipes.filter(r=>data.record[r.id]?.wrong).map(r=>r.id));
$('practice-cancel').onclick=()=>{
 if(!confirm('연습을 취소하고 첫 화면으로 돌아갈까요? 지금까지 체크한 연습 기록은 저장돼요.'))return;
 resetPractice();tab('practice');$('practice-setup').scrollIntoView({block:'start'});
};
