'use strict';
const ENCRYPTED_FORMAT='one-cup-encrypted-backup',BACKUP_ITERATIONS=600000;
function bytesToBase64(bytes){let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(s)}
function base64ToBytes(text){if(typeof text!=='string'||text.length>8000000)throw Error('format');return Uint8Array.from(atob(text),c=>c.charCodeAt(0))}
async function backupKey(password,salt,usage){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:BACKUP_ITERATIONS,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,[usage])}
async function encryptBackup(payload,password){const plain=new TextEncoder().encode(JSON.stringify(payload));if(plain.length>5000000)throw Error('size');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await backupKey(password,salt,'encrypt');const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain);return {format:ENCRYPTED_FORMAT,version:1,kdf:'PBKDF2-SHA256',iterations:BACKUP_ITERATIONS,cipher:'AES-256-GCM',salt:bytesToBase64(salt),iv:bytesToBase64(iv),ciphertext:bytesToBase64(new Uint8Array(encrypted))}}
async function decryptBackup(raw,password){if(raw.format!==ENCRYPTED_FORMAT||raw.version!==1||raw.kdf!=='PBKDF2-SHA256'||raw.iterations!==BACKUP_ITERATIONS||raw.cipher!=='AES-256-GCM')throw Error('format');const salt=base64ToBytes(raw.salt),iv=base64ToBytes(raw.iv),ciphertext=base64ToBytes(raw.ciphertext);if(salt.length!==16||iv.length!==12||ciphertext.length<16)throw Error('format');const key=await backupKey(password,salt,'decrypt');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,ciphertext);return JSON.parse(new TextDecoder().decode(plain))}
let backupAction='save',preparedBackup=null,lockedBackup=null,backupBusy=false;
function clearBackupDialog(){preparedBackup=null;lockedBackup=null;$('backup-password').value='';$('backup-password-again').value='';}
function openBackupDialog(action,locked=null){clearBackupDialog();backupAction=action;lockedBackup=locked;$('backup-password-title').textContent=locked?'백업 암호 입력':'백업 파일 암호 설정';$('backup-password-help').textContent=locked?'이 파일에 지정된 암호를 입력해야 불러올 수 있어요.':'암호를 입력하면 파일 내용이 암호화돼요. 비워 두면 일반 백업 파일로 만들어요. 암호를 잊으면 복구할 수 없어요.';$('backup-password-again-wrap').hidden=!!locked;$('backup-password').autocomplete=locked?'current-password':'new-password';$('backup-password-error').textContent='';$('backup-password-submit').textContent=locked?'잠금 해제':'백업 파일 준비';$('backup-password-fields').hidden=false;$('backup-ready').hidden=true;$('backup-password-dialog').showModal();$('backup-password').focus()}
function restoreFileBackup(raw){const d=normalizeBackup(raw);if(!d)throw Error('format');if(!confirm(`현재 레시피를 백업의 ${d.recipes.length}개 레시피로 바꿀까요? 기존 데이터를 보관하려면 먼저 백업해 주세요.`))return;data=d;const saved=save();list();resetPractice();if(saved)toast('백업을 불러왔어요.')}
$('export').onclick=()=>openBackupDialog('save');$('share-backup').onclick=()=>openBackupDialog('share');
$('backup-password-form').onsubmit=async e=>{e.preventDefault();if(backupBusy)return;const password=$('backup-password').value;if(lockedBackup&&!password){$('backup-password-error').textContent='암호를 입력해 주세요.';return;}if(!lockedBackup&&password!==$('backup-password-again').value){$('backup-password-error').textContent='두 암호가 일치하지 않아요.';return;}backupBusy=true;$('backup-password-submit').disabled=true;$('backup-password-cancel').disabled=true;$('backup-password-error').textContent=lockedBackup?'잠금을 해제하고 있어요…':'백업 파일을 준비하고 있어요…';try{if(lockedBackup){const raw=await decryptBackup(lockedBackup,password);restoreFileBackup(raw);$('backup-password-dialog').close();clearBackupDialog();}else{const payload=password?await encryptBackup(backupPayload(),password):backupPayload();preparedBackup=new File([JSON.stringify(payload)],'one-cup-'+(password?'encrypted-':'')+'backup-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json',{type:'application/json'});$('backup-password').value='';$('backup-password-again').value='';$('backup-password-fields').hidden=true;$('backup-ready').hidden=false;$('backup-password-error').textContent=password?'암호가 지정된 백업 파일이 준비됐어요.':'암호 없는 백업 파일이 준비됐어요.';$('backup-send').textContent=backupAction==='share'?'백업 파일 공유':'백업 파일 저장';}}catch(err){$('backup-password-error').textContent=lockedBackup?'암호가 맞지 않거나 파일이 손상됐어요. 암호를 확인하고 다시 시도해 주세요.':'백업 파일을 준비하지 못했어요. 다시 시도해 주세요.';}finally{backupBusy=false;$('backup-password-submit').disabled=false;$('backup-password-cancel').disabled=false;}};
$('backup-send').onclick=async()=>{if(!preparedBackup)return;try{if(backupAction==='share'){await navigator.share({files:[preparedBackup],title:'한 잔씩 레시피 백업'});}else{const url=URL.createObjectURL(preparedBackup),a=document.createElement('a');a.href=url;a.download=preparedBackup.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('백업 파일을 저장해 주세요.');}$('backup-password-dialog').close();clearBackupDialog();}catch(e){if(e.name!=='AbortError')$('backup-password-error').textContent='공유할 수 없어요. 아래 파일 저장 버튼을 이용해 주세요.';}};
$('backup-save-instead').onclick=()=>{backupAction='save';$('backup-send').onclick()};
$('backup-password-cancel').onclick=()=>{if(!backupBusy){$('backup-password-dialog').close();clearBackupDialog()}};
$('backup-password-dialog').addEventListener('cancel',e=>{if(backupBusy)e.preventDefault()});
$('backup-password-dialog').addEventListener('close',clearBackupDialog);
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>8000000)throw Error('size');const raw=JSON.parse((await file.text()).replace(/^\uFEFF/,''));if(raw?.format===ENCRYPTED_FORMAT)openBackupDialog('import',raw);else restoreFileBackup(raw);}catch{toast('올바른 레시피 백업 파일을 선택해 주세요.');}finally{e.target.value=''}};
