(()=>{const status=document.getElementById('offline-status'),button=document.getElementById('update-app'),refresh=document.getElementById('refresh-app'),dialog=document.getElementById('update-dialog'),apply=document.getElementById('update-now'),later=document.getElementById('update-later'),message=document.getElementById('update-message');let ready=false,registration,applying=false,lastError='',offeredWorker=null,applyTimer;
const paint=()=>{status.textContent=ready?(navigator.onLine?'✓ 오프라인 사용 준비 완료':'✓ 오프라인 모드 · 저장과 퀴즈 사용 가능'):lastError||(navigator.onLine?'오프라인 사용 준비 중…':'인터넷에 연결한 뒤 새로고침해 주세요.')};
function showUpdate(force=false){const worker=registration?.waiting;if(!worker||applying)return;button.hidden=false;if(!force&&offeredWorker===worker)return;if(document.querySelector('dialog[open]'))return;offeredWorker=worker;message.textContent='';apply.disabled=false;later.disabled=false;dialog.showModal();}
function applyUpdate(){const worker=registration?.waiting;if(!worker){message.textContent='새 버전 상태가 바뀌었어요. 설정에서 새로고침해 주세요.';return;}applying=true;apply.disabled=true;later.disabled=true;message.textContent='새 버전을 적용하고 있어요. 잠시 후 화면이 새로고침돼요.';worker.postMessage('ACTIVATE_UPDATE');clearTimeout(applyTimer);applyTimer=setTimeout(()=>{if(!applying)return;applying=false;apply.disabled=false;later.disabled=false;message.textContent='적용이 지연되고 있어요. 다시 시도하거나 설정에서 새로고침해 주세요.';},15000);}
apply.onclick=applyUpdate;later.onclick=()=>dialog.close();button.onclick=()=>showUpdate(true);dialog.addEventListener('cancel',e=>{if(applying)e.preventDefault()});
document.addEventListener('close',()=>showUpdate(),true);
refresh.onclick=()=>{if(registration?.waiting){showUpdate(true);return;}if(!confirm('화면을 새로고침할까요? 저장하지 않은 입력과 진행 중인 연습은 초기화돼요.'))return;location.reload()};
if(!('serviceWorker' in navigator)){status.textContent='이 브라우저는 오프라인 설치를 지원하지 않아요.';return}
navigator.serviceWorker.addEventListener('message',event=>{if(event.data?.type==='OFFLINE_ERROR'){lastError='오프라인 준비 실패: '+event.data.message;paint()}if(event.data?.type==='OFFLINE_READY'){ready=true;paint()}});
navigator.serviceWorker.addEventListener('controllerchange',()=>{ready=true;paint();if(applying){clearTimeout(applyTimer);location.reload();}else{button.hidden=true;if(dialog.open)dialog.close();}});
function checkUpdate(){if(navigator.onLine&&registration)registration.update().then(()=>showUpdate()).catch(()=>{});}
window.addEventListener('online',()=>{paint();checkUpdate()});window.addEventListener('offline',paint);window.addEventListener('focus',checkUpdate);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkUpdate()});
navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>{registration=r;showUpdate();const watch=worker=>worker?.addEventListener('statechange',()=>{if(worker.state==='installed')showUpdate();if(worker.state==='redundant'&&!ready){lastError=lastError||'오프라인 파일 저장 실패 · 새로고침으로 다시 시도해 주세요.';paint()}});watch(r.installing);r.addEventListener('updatefound',()=>watch(r.installing));return navigator.serviceWorker.ready}).then(()=>{ready=true;paint();navigator.storage?.persist?.().catch(()=>{})}).catch(e=>{lastError='오프라인 준비 실패 ('+e.name+') · 새로고침해 주세요.';paint()});paint();})();
