const CACHE_PREFIX='one-cup-offline-'+encodeURIComponent(new URL(self.registration.scope).pathname)+'-';
const CACHE=CACHE_PREFIX+'v7';
const REQUIRED=['./','./style.css','./recipe-tools.js','./app.js','./backup-crypto.js','./random-quiz.js','./offline.js'];
const OPTIONAL=['./creator-signature.png','./manifest.webmanifest','./icon-180.png','./icon-192.png','./icon-512.png'];
async function tell(message){for(const client of await self.clients.matchAll({type:'window',includeUncontrolled:true}))client.postMessage(message)}
async function download(path,cache){const url=new URL(path,self.registration.scope);const response=await fetch(new Request(url.href,{cache:'reload',credentials:'same-origin'}));if(!response.ok)throw Error(path+' HTTP '+response.status);if(new URL(response.url||url.href).origin!==url.origin)throw Error(path+' 로그인 확인 필요');if(path==='./'){const html=await response.clone().text();if(!html.includes('id="quiz-card"'))throw Error('앱 화면 대신 로그인 화면이 응답했어요.');}else if(path.endsWith('.js')||path.endsWith('.css')){if((response.headers.get('content-type')||'').includes('text/html'))throw Error(path+' 파일을 받지 못했어요.');}await cache.put(url.href,response)}
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE);try{for(const path of REQUIRED)await download(path,cache)}catch(e){await tell({type:'OFFLINE_ERROR',message:e.message});throw e}await Promise.allSettled(OPTIONAL.map(path=>download(path,cache)));})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith(CACHE_PREFIX)&&key!==CACHE)await caches.delete(key);await self.clients.claim();await tell({type:'OFFLINE_READY'});})()));
self.addEventListener('message',event=>{if(event.data==='ACTIVATE_UPDATE')self.skipWaiting()});
self.addEventListener('fetch',event=>{const req=event.request,url=new URL(req.url);if(req.method!=='GET'||url.origin!==self.location.origin)return;const root=new URL('./',self.registration.scope);if(url.pathname===new URL('./index.html',root).pathname){event.respondWith((async()=>await(await caches.open(CACHE)).match(root.href)||fetch(req))());return}const allowed=[...REQUIRED,...OPTIONAL].some(path=>new URL(path,root).pathname===url.pathname);if(!allowed)return;event.respondWith((async()=>{const cached=await(await caches.open(CACHE)).match(req,{ignoreSearch:true});return cached||fetch(req);})())});
